export const REQ_SCHEDULE_DATA = 'REQ_SCHEDULE_DATA';
export const REQ_SCHEDULE_DATA_SUCCEEDED = 'REQUESTED_DOG_SUCCEEDED';
export const REQ_SCHEDULE_DATA_FAILED = 'REQ_SCHEDULE_DATA_FAILED';
export const FETCHED_SCHEDULE_DATA = 'FETCHED_SCHEDULE_DATA';
export const TIME_ZONE = 'CHANGE_TIME_ZONE';
export const SCHEDULE_MODE = 'SCHEDULE_MODE';
export const WEEK = 'WEEK';
export const USER_MODE = 'USER_MODE';

